version: 2

updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "00:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
    groups:
      gradle-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "00:00"
      timezone: Europe/Berlin
    commit-message:
      prefix: chore
      include: scope
    groups:
      actions-minor-and-patch:
        update-types:
          - minor
          - patch
